name: CD FALSO
on:
  workflow_dispatch:
      inputs:
          ambiente:
              type: choice
              options:
                  - homologacao 
                  - producao
jobs:
  fake-deploy:
        runs-on: ubuntu-latest
        environment: ${{  inputs.ambiente }}
        steps:
            - name: Fake de deploy em ambiente
              run: echo "Deploy Realizado no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"
