name: CD FALSO
on:
  workflow_dispatch:
jobs:
  fake-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Fake de deploy em ambiente
              run: echo "Deploy Realizado no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"
